# Generated by Django 4.1.5 on 2023-01-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='email',
            field=models.CharField(default='rr21phe0016@student.nitw.ac.in', max_length=40),
        ),
    ]
