# Generated by Django 4.1.5 on 2023-01-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repo', '0002_alter_question_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='document',
            field=models.FileField(upload_to='static/Question-Papers'),
        ),
    ]
