# Generated by Django 4.1.5 on 2023-01-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repo', '0003_alter_question_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='document',
            field=models.FileField(upload_to='Question-Papers'),
        ),
    ]
